import os
from pathlib import Path
from loader import load_json5

# ── Structural constants (not user-tunable) ────────────────────────────────────
TERRAIN_OCEAN    = 0
TERRAIN_MOUNTAIN = 1
TERRAIN_PLAIN    = 2
TERRAIN_FOREST   = 3
TERRAIN_RIVER    = 4
TERRAIN_DESERT   = 5

TERRAIN_NAMES = {0:'Ocean',1:'Mountain',2:'Plain',3:'Forest',4:'River',5:'Desert'}

RES_FOOD  = 0
RES_WOOD  = 1
RES_METAL = 2
RES_GOLD  = 3
NUM_RESOURCES = 4
RESOURCE_NAMES   = ['Food', 'Wood', 'Metal', 'Gold']
RESOURCE_SYMBOLS = ['f', 'w', 'm', 'g']

MAP_SIZE   = 100
OUTER_SIZE = 10
INNER_SIZE = 10


RESET = '\033[0m'
BOLD  = '\033[1m'
DIM   = '\033[2m'

NATION_COLORS = [
    '\033[91m',  # Bright Red
    '\033[94m',  # Bright Blue
    '\033[92m',  # Bright Green
    '\033[93m',  # Bright Yellow
    '\033[95m',  # Bright Magenta
    '\033[96m',  # Bright Cyan
]

TERRAIN_COLORS = {
    TERRAIN_OCEAN:    '\033[34m',
    TERRAIN_MOUNTAIN: '\033[90m',
    TERRAIN_PLAIN:    '\033[32m',
    TERRAIN_FOREST:   '\033[32m',
    TERRAIN_RIVER:    '\033[36m',
    TERRAIN_DESERT:   '\033[33m',
}

TERRAIN_CHARS = {
    TERRAIN_OCEAN:    '~',
    TERRAIN_MOUNTAIN: '^',
    TERRAIN_PLAIN:    '.',
    TERRAIN_FOREST:   'T',
    TERRAIN_RIVER:    '~',
    TERRAIN_DESERT:   '_',
}

# ── Tunable balance constants (loaded from data/balance.json5) ─────────────────
_DATA = Path(__file__).parent / 'data'
_b = load_json5(_DATA / 'balance.json5')

START_GOLD  = _b['START_GOLD']
START_FOOD  = _b['START_FOOD']
START_WOOD  = _b['START_WOOD']
START_METAL = _b['START_METAL']

PROD_FARM        = _b['PROD_FARM']
PROD_FOREST_TILE = _b['PROD_FOREST_TILE']
PROD_MINE        = _b['PROD_MINE']
PROD_GOLD_TILE   = _b['PROD_GOLD_TILE']

ARMY_COST_FOOD  = _b['ARMY_COST_FOOD']
ARMY_COST_WOOD  = _b['ARMY_COST_WOOD']
ARMY_COST_METAL = _b['ARMY_COST_METAL']
ARMY_COST_GOLD  = _b['ARMY_COST_GOLD']

ARMY_UPKEEP_FOOD  = _b['ARMY_UPKEEP_FOOD']
ARMY_UPKEEP_METAL = _b['ARMY_UPKEEP_METAL']
ARMY_UPKEEP_GOLD  = _b['ARMY_UPKEEP_GOLD']

DEV_FARM_WOOD    = _b['DEV_FARM_WOOD']
DEV_FARM_FOOD    = _b['DEV_FARM_FOOD']
DEV_MINE_WOOD    = _b['DEV_MINE_WOOD']
DEV_MINE_METAL   = _b['DEV_MINE_METAL']
DEV_CASTLE_WOOD  = _b['DEV_CASTLE_WOOD']
DEV_CASTLE_METAL = _b['DEV_CASTLE_METAL']
DEV_ROAD_WOOD    = _b['DEV_ROAD_WOOD']
DEV_ROAD_METAL   = _b['DEV_ROAD_METAL']

TOWN_RADIUS       = _b['TOWN_RADIUS']
TOWN_MAX_ARMY_LVL = _b['TOWN_MAX_ARMY_LVL']
TOWN_GROWTH_POP   = _b['TOWN_GROWTH_POP']
POP_GROWTH_BASE   = _b['POP_GROWTH_BASE']
POP_GROWTH_FOOD   = _b['POP_GROWTH_FOOD']

GOLD_TRANSPORT_RATE = _b['GOLD_TRANSPORT_RATE']

SPD_PLAIN = _b['SPD_PLAIN']
SPD_ROAD  = _b['SPD_ROAD']
SPD_OCEAN = _b['SPD_OCEAN']
SPD_RIVER = _b['SPD_RIVER']

COMBAT_ATK_DICE  = _b['COMBAT_ATK_DICE']
COMBAT_DEF_DICE  = _b['COMBAT_DEF_DICE']
CASTLE_DEF_BONUS = _b['CASTLE_DEF_BONUS']

PEACE_MIN_TURNS      = _b['PEACE_MIN_TURNS']
WAR_COOLDOWN         = _b['WAR_COOLDOWN']
ALLIANCE_MAX         = _b['ALLIANCE_MAX']
ALLIANCE_COOLDOWN    = _b['ALLIANCE_COOLDOWN']
ALLIANCE_BETRAYAL_CD = _b['ALLIANCE_BETRAYAL_CD']

ALLIANCE_TIER_AGES  = _b['ALLIANCE_TIER_AGES']
ALLIANCE_MUTUAL_DEF = _b['ALLIANCE_MUTUAL_DEF']
ALLIANCE_DIVIDEND   = _b['ALLIANCE_DIVIDEND']

BETRAYAL_PLUNDER_RATE    = _b['BETRAYAL_PLUNDER_RATE']
BETRAYAL_REP_TURNS       = _b['BETRAYAL_REP_TURNS']
BETRAYAL_SURGE_TURNS     = _b['BETRAYAL_SURGE_TURNS']
BETRAYAL_ALLY_CHANCE_MOD = _b['BETRAYAL_ALLY_CHANCE_MOD']

AI_AGGRO_RATIO  = _b['AI_AGGRO_RATIO']
AI_LOW_RESOURCE = _b['AI_LOW_RESOURCE']
AI_HIGH_RESOURCE= _b['AI_HIGH_RESOURCE']
AI_TRADE_CHANCE = _b['AI_TRADE_CHANCE']
AI_ALLY_CHANCE  = _b['AI_ALLY_CHANCE']

UNION_VOTE_MIN_AGE    = _b['UNION_VOTE_MIN_AGE']
UNION_VOTE_CHANCE     = _b['UNION_VOTE_CHANCE']
UNION_SUCCESS_CHANCE  = _b['UNION_SUCCESS_CHANCE']
UNION_FAIL_BAD_CHANCE = _b['UNION_FAIL_BAD_CHANCE']
UNION_COOLDOWN_TURNS  = _b['UNION_COOLDOWN_TURNS']

SURRENDER_TILE_THRESHOLD = _b['SURRENDER_TILE_THRESHOLD']
SURRENDER_STRENGTH_RATIO = _b['SURRENDER_STRENGTH_RATIO']
SURRENDER_CHANCE         = _b['SURRENDER_CHANCE']
REBELLION_COOLDOWN_TURNS = _b['REBELLION_COOLDOWN_TURNS']

NUM_NATIONS         = _b['NUM_NATIONS']
MIN_NATION_DISTANCE = _b['MIN_NATION_DISTANCE']

LOG_MAX        = _b['LOG_MAX']
BATTLE_LOG_MAX = 100
CHART_HISTORY  = _b['CHART_HISTORY']
TURN_DELAY     = _b['TURN_DELAY']
WINDOW_WIDTH   = _b['WINDOW_WIDTH']
WINDOW_HEIGHT  = _b['WINDOW_HEIGHT']
